name: doc tests

on:
  pull_request:
  push:
    branches:
      - quantum_SHO_ci_test

jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e ".[dev]"

      - name: Run doctests
        run: pytest --doctest-modules physika/codegen.py physika/type_checker.py physika/utils/ tests/test_gradients/ -v --tb=short
